### ISSUE TITLE
Minnesota state

### ISSUE THREAD

**Issue by kjschiroo** [OpenTwinCities/mnpay#31]
We don't have a data set for 2016 yet listed at https://mn.gov/mmb/transparency-mn/payrolldata.jsp. I've sent an email to info.mmb@state.mn.us asking when they intend to update the data set.

**Comment by kjschiroo** [comment]
No responses so far, sent another email to try to get them to update.

**Comment by kjschiroo** [comment]
Kacey Chavez (651.201.8000) got back to me. They don't have an exact date at the moment since they are waiting on approval from their Commissioners office, but right now it is scheduled to be posted in the first week of January.

**Comment by eebbesen** [comment]
Duplicate -- now one for 2018
