### ISSUE TITLE
Minneapolis Park Board Salary Data

### ISSUE THREAD

**Issue by anton612** [OpenTwinCities/mnpay#46]
Attached is salary data from 2007 to present date in 2017 for the Minneapolis Park Board.

[mprbdatarequest1.zip](https://github.com/OpenTwinCities/mnpay/files/968316/mprbdatarequest1.zip)

**Comment by kjschiroo** [comment]
Thanks for your contribution! I know this is coming late, but it has now been incorporated into the published data set.
http://www.mnpay.org/?agency=Minneapolis+Park+Board&order=-wage&page=1
